In [1]:
!pip list or conda list

Package                            Version
---------------------------------- -------------------
absl-py                            1.0.0
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-navigator                 1.10.0
anaconda-project                   0.8.3
argh                               0.26.2
argon2-cffi                        20.1.0
asn1crypto                         1.4.0
astroid                            2.4.2
astropy                            4.0.2
astunparse                         1.6.3
async-generator                    1.10
atomicwrites                       1.4.0
attrs                              20.3.0
autopep8                           1.5.4
Babel                              2.8.1
backcall                           0.2.0
backports.functools-lru-cache      1.6.1
backports.shutil-get-terminal-size 1.0.0
backports.tempfile                 1.0
backports.weakref                  1.0.post1
bcrypt                             

In [7]:
!pip install opencv-python 

  Using cached opencv_python-4.5.4.60-cp38-cp38-win_amd64.whl (35.1 MB)


In [3]:
import cv2 
import os 
from PIL import Image 
import numpy as np 

In [4]:
image_directory = 'Brain tumor detection datasets/' 
no_tumor_images = os.listdir(image_directory + 'no/')
yes_tumor_images = os.listdir(image_directory + 'yes/')
dataset = []
label = []
#print(no_tumor_images) 
#path='no0.jpg' 
#print(path.split('.')[1]) 

for i , image_name in enumerate(no_tumor_images): 
    if(image_name.split('.')[1]=='jpg'): 
        image=cv2.imread(image_directory+'no/'+image_name) 
        image=Image.fromarray(image, 'RGB') 
        image=image.resize((64,64)) 
        dataset.append(np.array(image))
        label.append(0)
        
for i , image_name in enumerate(yes_tumor_images): 
    if(image_name.split('.')[1]=='jpg'): 
        image=cv2.imread(image_directory+'yes/'+image_name) 
        image=Image.fromarray(image, 'RGB') 
        image=image.resize((64,64)) 
        dataset.append(np.array(image))    
        label.append(1)
        
print(len(dataset))
print(len(label))


3000
3000


In [5]:
from sklearn.model_selection import train_test_split
dataset= np.array(dataset)
label= np.array(label)
x_train, x_test, y_train, y_test = train_test_split(dataset, label, test_size=0.2, random_state=0)
print(x_train.shape)
print(y_train.shape)

# Reshape = (n, image_width, image_height, n_channel)

(2400, 64, 64, 3)
(2400,)


In [6]:
print(x_test.shape)
print(y_test.shape)

(600, 64, 64, 3)
(600,)


In [7]:
!pip install tensorflow

In [8]:
import tensorflow as tf
from tensorflow import keras
#from keras.utils import normalize 
from keras.utils.np_utils import normalize

from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense

In [9]:
x_train= normalize(x_train, axis=1)
x_test= normalize(x_test, axis=1)

#Model Building
#64,64,3
 
model = Sequential()

model.add(Conv2D(32, (3,3), input_shape=(64,64,3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(32, (3,3), kernel_initializer='he_uniform'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(64, (3,3), kernel_initializer='he_uniform'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Flatten())
model.add(Dense(64))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(1))
model.add(Activation('sigmoid'))

In [10]:
#Binary CrossEntroy = 1, sigmoid
#Categorical CrossEntropy = 2, softmax
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_train, y_train,
         batch_size=16,
         verbose=1, epochs=10,
         validation_data=(x_test, y_test),shuffle=False)
model.save('BrainTumor10Epochs.h5')

Epoch 1/10
150/150 [==============================] - 12s 59ms/step - loss: 0.5224 - accuracy: 0.7554 - val_loss: 0.4304 - val_accuracy: 0.8167
Epoch 2/10
150/150 [==============================] - 8s 52ms/step - loss: 0.3739 - accuracy: 0.8450 - val_loss: 0.3263 - val_accuracy: 0.8617
Epoch 3/10
150/150 [==============================] - 8s 56ms/step - loss: 0.2858 - accuracy: 0.8875 - val_loss: 0.2669 - val_accuracy: 0.8867
Epoch 4/10
150/150 [==============================] - 9s 60ms/step - loss: 0.2033 - accuracy: 0.9262 - val_loss: 0.1711 - val_accuracy: 0.9333
Epoch 5/10
150/150 [==============================] - 10s 68ms/step - loss: 0.1352 - accuracy: 0.9592 - val_loss: 0.1363 - val_accuracy: 0.9567
Epoch 6/10
150/150 [==============================] - 10s 67ms/step - loss: 0.0925 - accuracy: 0.9679 - val_loss: 0.0952 - val_accuracy: 0.9717
Epoch 7/10
150/150 [==============================] - 9s 60ms/step - loss: 0.0595 - accuracy: 0.9817 - val_loss: 0.0816 - val_accuracy: 0.9

In [11]:
#Categorical crossEntropy
from keras.utils.np_utils import to_categorical
x_train= normalize(x_train, axis=1)
x_test= normalize(x_test, axis=1)

y_train=to_categorical(y_train, num_classes=2)
y_test=to_categorical(y_test, num_classes=2)


#Model Building
#64,64,3
 
model = Sequential()

model.add(Conv2D(32, (3,3), input_shape=(64,64,3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(32, (3,3), kernel_initializer='he_uniform'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(64, (3,3), kernel_initializer='he_uniform'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Flatten())
model.add(Dense(64))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(2))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_train, y_train,
         batch_size=16,
         verbose=1, epochs=10,
         validation_data=(x_test, y_test),shuffle=False)
model.save('BrainTumor10EpochsCategorical.h5')

Epoch 1/10
150/150 [==============================] - 10s 57ms/step - loss: 0.5523 - accuracy: 0.7167 - val_loss: 0.4417 - val_accuracy: 0.7917
Epoch 2/10
150/150 [==============================] - 8s 56ms/step - loss: 0.3892 - accuracy: 0.8350 - val_loss: 0.3197 - val_accuracy: 0.8550
Epoch 3/10
150/150 [==============================] - 8s 56ms/step - loss: 0.2828 - accuracy: 0.8863 - val_loss: 0.2565 - val_accuracy: 0.8850
Epoch 4/10
150/150 [==============================] - 8s 55ms/step - loss: 0.2058 - accuracy: 0.9200 - val_loss: 0.1688 - val_accuracy: 0.9417
Epoch 5/10
150/150 [==============================] - 8s 54ms/step - loss: 0.1461 - accuracy: 0.9463 - val_loss: 0.1370 - val_accuracy: 0.9483
Epoch 6/10
150/150 [==============================] - 9s 59ms/step - loss: 0.0901 - accuracy: 0.9737 - val_loss: 0.1097 - val_accuracy: 0.9633
Epoch 7/10
150/150 [==============================] - 9s 57ms/step - loss: 0.0606 - accuracy: 0.9817 - val_loss: 0.0967 - val_accuracy: 0.968

In [12]:
import cv2
import numpy as np
from keras.models import load_model
from PIL import Image
from tensorflow.keras.models import Sequential

In [13]:
model=load_model('BrainTumor10Epochs.h5')
image=cv2.imread('C:\\Users\\s\\Research\\Brain tumor detection datasets\\pred\\pred58.jpg')
img=Image.fromarray(image)
img=img.resize((64,64))
img=np.array(img)
print(img)

[[[32 32 32]
  [32 32 32]
  [32 32 32]
  ...
  [32 32 32]
  [32 32 32]
  [32 32 32]]

 [[32 32 32]
  [32 32 32]
  [32 32 32]
  ...
  [32 32 32]
  [32 32 32]
  [32 32 32]]

 [[32 32 32]
  [32 32 32]
  [32 32 32]
  ...
  [32 32 32]
  [32 32 32]
  [32 32 32]]

 ...

 [[32 32 32]
  [32 32 32]
  [32 32 32]
  ...
  [32 32 32]
  [32 32 32]
  [32 32 32]]

 [[32 32 32]
  [32 32 32]
  [32 32 32]
  ...
  [32 32 32]
  [32 32 32]
  [32 32 32]]

 [[32 32 32]
  [32 32 32]
  [32 32 32]
  ...
  [32 32 32]
  [32 32 32]
  [32 32 32]]]


In [73]:
import tensorflow as tf
from tensorflow.keras.preprocessing import image

model=load_model('BrainTumor10Epochs.h5')
image=cv2.imread('C:\\Users\\s\\Research\\Brain tumor detection datasets\\pred\\pred6.jpg')
img=Image.fromarray(image)
img=img.resize((64,64))

img=np.array(img)

input_img=np.expand_dims(img, axis=0)

img_preprocessed = preprocess_input(input_img)
prediction = model.predict(img_preprocessed)

print(prediction)

NameError: name 'preprocess_input' is not defined